// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCityMyPlaces.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyCityMyPlaces.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MyCityMyPlaces.Models.Family", b =>
                {
                    b.Property<int>("idFamily")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("idRelatedMember")
                        .HasColumnType("integer");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.HasKey("idFamily");

                    b.HasIndex("idUser");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("MyCityMyPlaces.Models.Location", b =>
                {
                    b.Property<int>("idLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("comment")
                        .HasColumnType("text");

                    b.Property<decimal>("coordinateX")
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("coordinateY")
                        .HasColumnType("decimal(8,6)");

                    b.Property<int>("idUser")
                        .HasColumnType("integer");

                    b.Property<string>("locationName")
                        .HasColumnType("text");

                    b.Property<bool>("visible")
                        .HasColumnType("boolean");

                    b.HasKey("idLocation");

                    b.HasIndex("idUser");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MyCityMyPlaces.Models.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("idUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MyCityMyPlaces.Models.Family", b =>
                {
                    b.HasOne("MyCityMyPlaces.Models.User", "User")
                        .WithMany("Families")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityMyPlaces.Models.Location", b =>
                {
                    b.HasOne("MyCityMyPlaces.Models.User", "User")
                        .WithMany("Locations")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyCityMyPlaces.Models.User", b =>
                {
                    b.Navigation("Families");

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
